### ISSUE TITLE
DRIVE and TUNE_DRIVE error

### ISSUE THREAD

**Issue by VK6NX** [dkaukov/tci-mqtt-gateway#2]
when sending 'tune_drive' or 'drive' to  'to-sdr' topic, the TCI DRIVE reflected only.

It has to be matching:  'tune_drive' (JSON) to 'TUNE_DRIVE' (TCI) and 'drive' (JSON) to 'DRIVE' (TCI)

**Comment by dkaukov** [comment]
Hmm.. This is strange. We have tests testing exactly that:
https://github.com/dkaukov/tci-mqtt-gateway/blob/main/test/tci-serializer.spec.js#L23
https://github.com/dkaukov/tci-mqtt-gateway/blob/main/test/tci-serializer.spec.js#L26

Can you provide payloads and logs?

**Comment by VK6NX** [comment]
Здрась, опомнились :)
Я уже все починил давно. См апдейт в Firmware
